name = "blog"
compatibility_date = "2025-07-31"

[build]
command = "chmod a+x build.sh && ./build.sh"

[assets]
directory = "./public"
not_found_handling = "404-page"

[[routes]]
pattern = "blog.melraeven.nl"
custom_domain = true
